export const MAX_PATCHES_PER_COMMAND = 128;
export const MAX_ELEMENTS_PER_DELETE = 128;
export const MAX_REPAIRED_ARROWS_PER_COMMAND = 512;
export const MAX_CHANGESET_BYTES = 1_000_000;
export const MAX_POINTS_PER_STROKE = 8_192;
export const MAX_IN_MEMORY_PROCESSED_REQUESTS = 1_000;
